In [1]:
import numpy as np

## Основні операції перетворень

### 1. Обертання

In [2]:
def rotate(theta):
    theta = theta * np.pi / 180
    return np.array([
        [np.cos(theta), -np.sin(theta), 0],
        [np.sin(theta), np.cos(theta), 0],
        [0, 0, 1]
    ])

### 2. Переміщення

In [3]:
def move(x, y):
    return np.array([
        [1, 0, x],
        [0, 1, y],
        [0, 0, 1]
    ])

### 3. Масштабування

In [4]:
def scale(x, y):
    return np.array([
        [x, 0, 0],
        [0, y, 0],
        [0, 0, 1]
    ])

### 4. Розрахунок матриці транформації

In [5]:
def modelMatrix(args, sequence):
    # V(x, y, 1)
    V = np.array(args['V'] + (1,))
    # calculate transformation matrix for each operation
    Tr = {}
    Tr['R'] = rotate( args['R'])
    Tr['T'] = move  (*args['T']) # use `*`` to decompose a list into separate arguments
    Tr['S'] = scale (*args['S'])
    # calculate a transformation matrix for the `sequence`
    T = np.identity(3)
    for op in sequence:
        T = T @ Tr[op]
    # apply the transformation matrix to the input vector `V`
    Vtr = T @ V
    return Vtr

## Розрахунок (приклад з методички)

In [6]:
inMatrix = {
    'R': 33,
    'T': (1, 2),
    'S': (2, 1.2),
    'V': (1, 2),
}
modelMatrix(inMatrix, 'SRT')

array([-1.00243001,  5.33275241,  1.        ])

In [7]:
inMatrix = {
    'R': 16,
    'T': (1, 2),
    'S': (1, 2),
    'V': (1, 2),
}
modelMatrix(inMatrix, 'TRS')

array([0.85871227, 6.12068414, 1.        ])

## Розрахунок (варіант 2)

In [8]:
inMatrix = {
    'R': 12.6,
    'T': (2, 2),
    'S': (1, 2.2),
    'V': (3, 2),
}
modelMatrix(inMatrix, 'SRT')

array([ 4.00701084, 10.98764316,  1.        ])

In [9]:
inMatrix = {
    'R': 36.4,
    'T': (1, 1),
    'S': (1.3, 1.2),
    'V': (3, 2),
}
modelMatrix(inMatrix, 'TRS')

array([2.71488048, 5.24607877, 1.        ])

## Розрахунок (варіант 3)

In [10]:
inMatrix = {
    'R': 15,
    'T': (2, 2),
    'S': (1.5, 2.7),
    'V': (6, 2),
}
modelMatrix(inMatrix, 'SRT')

array([10.03819564, 16.0224903 ,  1.        ])

In [11]:
inMatrix = {
    'R': 51,
    'T': (3, 2),
    'S': (1, 3.2),
    'V': (6, 2),
}
modelMatrix(inMatrix, 'TRS')

array([ 1.80218819, 10.69052627,  1.        ])