In [1]:
import numpy as np

In [2]:
population = np.array([56, 12, 66, 19, 32, 72, 27, 32])
population

array([56, 12, 66, 19, 32, 72, 27, 32])

In [3]:
mean = np.mean(population)
mean

39.5

In [4]:
deviations = population - mean
deviations

array([ 16.5, -27.5,  26.5, -20.5,  -7.5,  32.5, -12.5,  -7.5])

In [5]:
squared_deviations = deviations ** 2
squared_deviations

array([ 272.25,  756.25,  702.25,  420.25,   56.25, 1056.25,  156.25,
         56.25])

In [6]:
variance = np.mean(squared_deviations)
variance

434.5

In [7]:
standard_deviation = variance ** .5
standard_deviation

20.844663585675832